channels:
- conda-forge
dependencies:
- python=3.8.2
- pip
- pip:
  - azureml-core==1.34.0
  - azureml-mlflow==1.34.0
  - flatdict==4.0.1
  - mlflow==1.25.1 
  - torch==1.11.0
  - scikit-learn==0.23.1
  - numpy==1.18.5
  - scipy==1.4.1
  - pandas==1.1.5
  - tqdm==4.62.2
  - nltk==3.6.7
  - gensim==3.8.3
  - transformers==4.5.1